services:
  registry:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      PORT: "8090"
      POSTGRES_HOST: "10.125.208.41"
      POSTGRES_PORT: "5433"
      POSTGRES_DB: autopipe_wf
      POSTGRES_USER: autopipe
      POSTGRES_PASSWORD: autopipe123
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
